a: a.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g a.cpp -o build/a

b: b.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g b.cpp -o build/b

c: c.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g c.cpp -o build/c

d: d.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g d.cpp -o build/d

e: e.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g e.cpp -o build/e

f: f.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g f.cpp -o build/f

g: g.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g g.cpp -o build/g

h: h.cpp
	g++-10 --std=c++20 -Wall -Wextra -O2 -g h.cpp -o build/h

